### ISSUE TITLE
ModuleNotFoundError: No module named 'detect_features'

### ISSUE THREAD

**Issue by dyln** [hriddhidey/visage#3]
sample code does not see the detect_features module some how, but I can run the apply_makeup.py inside the package. do you have any suggestion? i have not installed it in virtualenv.
```
caners-MacBook-Pro:MILKLAB canereren$ python3 makeUpTest.py 
Traceback (most recent call last):
  File "makeUpTest.py", line 1, in <module>
    from visage import ApplyMakeup
  File "/Users/canereren/anaconda/lib/python3.6/site-packages/visage/__init__.py", line 6, in <module>
    from visage.apply_makeup import ApplyMakeup
  File "/Users/canereren/anaconda/lib/python3.6/site-packages/visage/apply_makeup.py", line 15, in <module>
    from detect_features  import DetectLandmarks
ModuleNotFoundError: No module named 'detect_features'
```

**Comment by dyln** [comment]
same with virtualenv
```
(cv) caners-MacBook-Pro:MILKLAB canereren$ python3 makeUpTest.py 
Traceback (most recent call last):
  File "makeUpTest.py", line 1, in <module>
    from visage import ApplyMakeup
  File "/Users/canereren/.virtualenvs/cv/lib/python3.6/site-packages/visage/__init__.py", line 6, in <module>
    from visage.apply_makeup import ApplyMakeup
  File "/Users/canereren/.virtualenvs/cv/lib/python3.6/site-packages/visage/apply_makeup.py", line 15, in <module>
    from  detect_features import DetectLandmarks
ModuleNotFoundError: No module named 'detect_features'
```

**Comment by dyln** [comment]
Solved it. merged two files, apply_makeup.py and detect_features.py.
and fixed the izips.

i can make a pull request if you want.

**Comment by hriddhidey** [comment]
Fixed by [https://github.com/hriddhidey/visage/commit/4d2fbd77c3c21e630f45aa5340b15691632eeafb](this), I believe. Thank you, @dyln .

**Comment by ghost** [comment]
same issue:
not fixed yet, 
Traceback (most recent call last):
  File "dlib.py", line 1, in <module>
    from visage import ApplyMakeup
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\visage\__init__.py", line 6, in <module>
    from visage.apply_makeup import ApplyMakeup
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\visage\apply_makeup.py", line 15, in <module>
    from  detect_features import DetectLandmarks
ModuleNotFoundError: No module named 'detect_features'
